# @package _global_
model:
  num_classes: 100

dataset:
  name: parity-subspace-dataset
  batch_size: 128
  val_split: 0.1
  num_workers: 4
  pin_memory: true
  enable_ffcv: false
  parity_subspace_dataset:
    num_samples_train: 50000
    num_samples_test: 10000
    d_intrinsic: 128
    d_ambient: 512
    modulo_base: 2
    data_seed_train: 345
    data_seed_test: 678
    projection_seed: 901
