# @package _global_
defaults:
  - model: mlp_mnist
  - dataset: mnist
  - optimizer: adamw
  - scheduler: none
  - training: default
  - interpolation: disabled
  - logging: console
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

# Multi-model experiment settings
num_models: 2

# Global settings
seed: null
init_seed: null  # Controls parameter initialization (defaults to random init seed per model). Can be list (seed per model) or number (same for all models).
mask_seed: null  # Controls parameter initialization (defaults to random mask seed per train.py run, but fixed between multiple models trained in the same training run, so they are compatible for LMC)
optimization_seed: null   # Controls optimizer state initialization (defaults to init_seed). Can be list (seed per model) or number (same for all models).
device: cuda
output_dir: ./outputs
experiment_name: ${now:%Y-%m-%d}/${now:%H-%M-%S}__${model.name}
max_parallel_processes: 10

# Hydra configuration
hydra:
  output_subdir: null
  run:
    dir: .

