defaults:
  - config  # inherits from base config.yaml
  - override logging: wandb
  - override dataset: cifar10
  - override model: resnet_cifar
  - override scheduler: resnet
  - _self_  # keeps specific-config overrides last
model:
  mask_params:
    default:
      mask_constant: 2.0
  symmetry: 3
training:
  num_epochs: 100
  save_every: 1
  cosine_similarity:
    enabled: false
  functional_similarity:
    enabled: false
interpolation:
  enabled: false
num_models: 16
optimizer:
  lr: 0.0001

max_parallel_processes: 4
